"""
backend/schemas.py
Project Capital Velocity — Pydantic Schema Gates

ARCHITECTURAL CONTRACT (NON-NEGOTIABLE — ZERO HALLUCINATION PROPAGATION):
- These Pydantic models are the HARD SCHEMA GATE between the deterministic math
  engines and the LLM narrator.
- The math engine produces a raw dict. We validate it against PricingOutput
  (and related models) BEFORE the LLM is called.
- If validation fails, Python raises ValidationError immediately. The LLM is
  never invoked. Zero hallucination propagation — the LLM cannot receive
  malformed context.
- The LLM function signature is: generate_narrative(pricing_data: PricingOutput)
  It accepts a TYPED Pydantic object, not a raw dict. The type system enforces
  the contract at every call site.

SCHEMA DISCIPLINE:
- StrictInt for all PSF values (no floats, no None, no strings)
- StrictStr for confidence (no numbers, no None)
- Validator enforces confidence ∈ {"High", "Medium", "Low"} exactly
- If the math engine produces None (e.g. no-match edge case), validation fails
  and the orchestrator catches the error before reaching the LLM
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, ValidationError, field_validator


# ---------------------------------------------------------------------------
# Core schema: PricingOutput — the gate between math and LLM
# ---------------------------------------------------------------------------

class PricingOutput(BaseModel):
    """
    The EXACT schema the LLM narrator must receive.

    StrictInt: rejects floats, None, strings — only integers pass.
    StrictStr: rejects None, numbers — only strings pass.
    The validator enforces confidence ∈ {"High", "Medium", "Low"} exactly.

    If the math engine produces anything that doesn't match this perfectly,
    Pydantic raises ValidationError BEFORE the LLM is called.
    """

    floor_psf: StrictInt
    optimal_psf: StrictInt
    ceiling_psf: StrictInt
    confidence: StrictStr  # Must be exactly "High", "Medium", or "Low"

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: str) -> str:
        if v not in ["High", "Medium", "Low"]:
            raise ValueError(
                f"Invalid confidence state generated by math engine: {v!r}. "
                f"Must be exactly 'High', 'Medium', or 'Low'."
            )
        return v

    model_config = ConfigDict(
        # Extra fields are forbidden — the LLM must not see unexpected data
        extra="forbid",
        # Validate on assignment too, not just on init
        validate_assignment=True,
    )


# ---------------------------------------------------------------------------
# Extended schemas for the other engine outputs
# ---------------------------------------------------------------------------

class ScenarioOutput(BaseModel):
    """Schema gate for a single scenario entry from the scenario engine."""
    scenario_name: StrictStr
    price_psf: StrictInt
    projected_absorption_days: StrictInt
    total_revenue_assumption: Optional[StrictInt] = None
    total_carry_cost: Optional[StrictInt] = None

    @field_validator("scenario_name")
    @classmethod
    def validate_scenario_name(cls, v: str) -> str:
        if v not in ["Aggressive", "Base", "Conservative"]:
            raise ValueError(f"Invalid scenario name: {v!r}")
        return v

    model_config = ConfigDict(extra="forbid")


class CashflowSummaryOutput(BaseModel):
    """Schema gate for the cashflow summary."""
    total_collected: StrictInt
    month_0_collected: StrictInt
    month_0_pct: StrictInt
    handover_collected: StrictInt
    handover_pct: StrictInt
    timeline_months: StrictInt

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Validation helper — the gate function
# ---------------------------------------------------------------------------

def validate_pricing_for_llm(raw_pricing: dict) -> PricingOutput:
    """
    Validate a raw pricing dict against the PricingOutput schema.

    This is the GATE. Call this right before invoking the LLM. If the math
    engine produced None values (no-match edge case), wrong types, or an
    invalid confidence string, this function raises ValidationError and the
    LLM is never called.

    Args:
        raw_pricing: dict with floor_psf, optimal_psf, ceiling_psf, confidence.
            All PSF values must be integers (not None, not float).
            confidence must be exactly "High", "Medium", or "Low".

    Returns:
        PricingOutput: the validated Pydantic object, safe to pass to the LLM.

    Raises:
        ValidationError: if any field fails validation. The orchestrator must
            catch this and return a structured error — NEVER pass malformed
            data to the LLM.
    """
    return PricingOutput(**raw_pricing)


def safe_validate_pricing_for_llm(raw_pricing: dict) -> tuple[Optional[PricingOutput], Optional[str]]:
    """
    Safe wrapper that returns (validated_object, None) on success or
    (None, error_message) on failure. Never raises.

    Use this in the orchestrator to gracefully handle validation failures
    without crashing the entire pipeline — the LLM narrator gets skipped
    with a [SCHEMA GATE FAILED] fallback instead.
    """
    try:
        validated = validate_pricing_for_llm(raw_pricing)
        return validated, None
    except ValidationError as e:
        error_msg = f"Schema gate validation failed: {e}"
        return None, error_msg
    except Exception as e:
        error_msg = f"Unexpected schema gate error: {type(e).__name__}: {e}"
        return None, error_msg


# ---------------------------------------------------------------------------
# Standalone self-validation
#   Run:  python backend/schemas.py
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=" * 78)
    print("PROJECT CAPITAL VELOCITY — SCHEMA GATE SELF-VALIDATION")
    print("=" * 78)

    test_cases = [
        {
            "name": "Valid pricing — should pass",
            "data": {"floor_psf": 2671, "optimal_psf": 2866, "ceiling_psf": 3116, "confidence": "Medium"},
            "should_pass": True,
        },
        {
            "name": "Valid pricing — High confidence",
            "data": {"floor_psf": 3036, "optimal_psf": 3258, "ceiling_psf": 3542, "confidence": "High"},
            "should_pass": True,
        },
        {
            "name": "Valid pricing — Low confidence",
            "data": {"floor_psf": 2208, "optimal_psf": 2369, "ceiling_psf": 2576, "confidence": "Low"},
            "should_pass": True,
        },
        {
            "name": "INVALID — None PSF (no-match edge case)",
            "data": {"floor_psf": None, "optimal_psf": None, "ceiling_psf": None, "confidence": "None"},
            "should_pass": False,
        },
        {
            "name": "INVALID — float PSF (StrictInt rejects)",
            "data": {"floor_psf": 2671.5, "optimal_psf": 2866.0, "ceiling_psf": 3116.2, "confidence": "Medium"},
            "should_pass": False,
        },
        {
            "name": "INVALID — confidence 'None' string",
            "data": {"floor_psf": 2671, "optimal_psf": 2866, "ceiling_psf": 3116, "confidence": "None"},
            "should_pass": False,
        },
        {
            "name": "INVALID — confidence lowercase 'medium'",
            "data": {"floor_psf": 2671, "optimal_psf": 2866, "ceiling_psf": 3116, "confidence": "medium"},
            "should_pass": False,
        },
        {
            "name": "INVALID — extra field (extra='forbid')",
            "data": {"floor_psf": 2671, "optimal_psf": 2866, "ceiling_psf": 3116, "confidence": "Medium", "rogue_field": "LLM should never see this"},
            "should_pass": False,
        },
        {
            "name": "INVALID — missing field",
            "data": {"floor_psf": 2671, "optimal_psf": 2866, "confidence": "Medium"},
            "should_pass": False,
        },
    ]

    passed = 0
    failed = 0

    for tc in test_cases:
        print(f"\n--- {tc['name']} ---")
        print(f"  Input: {tc['data']}")
        validated, error = safe_validate_pricing_for_llm(tc["data"])
        if tc["should_pass"]:
            if validated is not None:
                print(f"  ✓ PASSED — validated: {validated}")
                passed += 1
            else:
                print(f"  ✗ UNEXPECTED FAILURE: {error}")
                failed += 1
        else:
            if validated is None:
                print(f"  ✓ CORRECTLY REJECTED: {error[:80]}...")
                passed += 1
            else:
                print(f"  ✗ SHOULD HAVE FAILED but passed: {validated}")
                failed += 1

    print(f"\n{'=' * 78}")
    print(f"RESULTS: {passed} passed, {failed} failed out of {len(test_cases)}")
    print(f"{'=' * 78}")

    if failed == 0:
        print("\n✓ Schema gate is airtight. The LLM can never receive:")
        print("  - None values (no-match edge case)")
        print("  - Float PSF values (StrictInt rejects)")
        print("  - Invalid confidence strings (validator enforces exact match)")
        print("  - Extra fields (extra='forbid')")
        print("  - Missing fields (required by default)")
        print("\n  Zero hallucination propagation. The gate holds.")
    else:
        print("\n✗ SCHEMA GATE HAS HOLES — fix the failures above.")

    print(f"{'=' * 78}")
